use_frameworks!

platform :ios, '9.0'

target 'FlutterPodSDK_Example' do
  pod 'FlutterPodSDK', :path => '../'

  target 'FlutterPodSDK_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
